name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Convert repo owner and name to lowercase
      - name: Set lowercase image variables
        id: vars
        run: |
          echo "OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "REPO=$(echo '${{ github.event.repository.name }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build & Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER }}/${{ env.REPO }}:latest
            ghcr.io/${{ env.OWNER }}/${{ env.REPO }}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set lowercase image variables
        id: vars
        run: |
          echo "OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "REPO=$(echo '${{ github.event.repository.name }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Update Kubernetes manifests
        run: |
          sed -i "s|ghcr.io/.*/.*:.*|ghcr.io/${{ env.OWNER }}/${{ env.REPO }}:latest|g" k8s/deployment.yaml

      # ✅ Start Minikube inside the GitHub Actions runner
      - name: Start Minikube
        uses: medyagh/setup-minikube@latest

      # ✅ Load the newly built image into Minikube (optional but recommended)
      - name: Load image into Minikube
        run: |
          minikube image load ghcr.io/${{ env.OWNER }}/${{ env.REPO }}:latest

      # ✅ Deploy manifests to Minikube
      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      # ✅ Verify the deployment
      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/nextjs-deployment
          kubectl get pods -o wide
